Repository Goonco/crews-client, pull requests merged in 2023-11, with the labels that each got.

#21 지원서 평가페이지 UI &기능, 지원서 상세평가페이지 UI 구현
  src/Router.js
  src/components/molecules/Navigation.jsx
  src/pages/Evaluate/ApplyItem.js
  src/pages/Evaluate/ApplyListSection.js
  src/pages/Evaluate/BottomBar.js
  src/pages/Evaluate/EvaluateSummarySection.js
  src/pages/Evaluate/backArrow.svg
  src/pages/Evaluate/downArrow.svg
  src/pages/Evaluate/index.jsx
  src/pages/Evaluate/select.svg
  src/pages/EvaluteDetail/ApplicationSection.js
  src/pages/EvaluteDetail/AssessSection.js
  src/pages/EvaluteDetail/EvaluateDetailHeader.js
  src/pages/EvaluteDetail/backArrow.svg
  src/pages/EvaluteDetail/beforeArrow.svg
  src/pages/EvaluteDetail/index.jsx
  src/pages/EvaluteDetail/nextArrow.svg
  src/pages/MakePost/ImageSection.js
  src/pages/index.js
Labels: ✨ Feature

#33 [1.로그인] 백엔드 연동 구현 완료
  src/api/request.js
  src/pages/Login/CollaboCrews.jsx
  src/pages/Login/LoginHeader.jsx
  src/pages/Login/LoginInput.jsx
  src/pages/Login/LoginOptions.jsx
  src/pages/Login/eye.svg
  src/pages/Login/eyeX.svg
  src/pages/Login/index.jsx
Labels: ✨ Feature, :lipstick: UI Styling

#42 [1. 로그인] 아이콘 겹침 문제 해결
  src/components/atoms/Input.jsx
  src/pages/Login/LoginInput.jsx
Labels: :lipstick: UI Styling
